name: Hello Flow
on:
 schedule:
  - cron: '*/5 * * * *'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Diga oi!
      run: echo "Hey everyone!"
    - name: Diga valeu
      run: echo "Por hoje é só pessoal! vlw, flw"
